### ISSUE TITLE
Hiányzó licenc

### ISSUE THREAD

**Issue by floridan95** [diatar/diatar-android#1]
Sziasztok!

Örülök, hogy felkerült ide is ennek a hasznos alkalmazásnak a forrása. 

A repóban nem találtam rá utalást, hogy milyen licenc vonatkozik a program Android verziójára és a diatar-dtxs repóban lévő énekeskönyvek tartalmára sem. Az asztali verzió esetében láttam csak egyértelműen jelezve, a GPLv3-as licencet.

Milyen licenc alatt lesz várható az alkalmazás, vagy marad source-available formában?

Üdv:
floridan

**Comment by borazslo** [comment]
@polyJoe ? azaz hoze(kukac)diatar.eu ?

(Én kezelem a github accountot. Hozé a nagyfőnök. Én még csak épp elkezdtem a besegítést.)

**Comment by polyJoe** [comment]
Szia, erre még nem reagáltam:
igen, polyJoe vagyok (valaki már foglalta a Hoze nevet :D )
Köszi!

diatar ***@***.***> ezt írta (időpont: 2023. okt. 27., P,
0:58):

**Comment by polyJoe** [comment]
> Az asztali verzió esetében láttam csak egyértelműen jelezve, a GPLv3-as licencet.

Szia, igen, GPLv3 ide is jó (legalábbis remélem!), még csak most kezdtük elrendezni a giten, majd ezt is gatyába rázzuk.
Üdv: Hozé

**Comment by polyJoe** [comment]
Feltettem a COPYING fájlt, a GPLv3 licenc szöveggel.
